/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package nkk.scraper

import org.jsoup.Jsoup
import org.jsoup.nodes.Element

const val goldenURL = "https://retrieverklubben.no/golden-retriever/oppdretterliste/"

// CSS selectors
const val sectionSelector = "body > div.main_container > div.oppdretterliste_section"
const val breederListClass = "oppdretterliste_post_container"
fun getFylke(it: Element): Fylke? {
  val content = it.select("h5").first()
  return when (content) {
    null -> null
    else -> Fylke.values().first { it.fullName == content.text() }
  }
}

fun getBreeders(element: Element, fylke: Fylke): List<Breeder> =
  element
    .select("div.oppdretterliste_box")
    .map {row ->
      row
        .select("p > span")
        .map { it.text().split(":") }
        .filter { it.size == 2 }
        .map { it[0] to it[1] }
        .toBreeder(fylke)
    }


fun printBreederTable(url: String) {
  val breeders = Jsoup
    .connect(url)
    .get()
    .select(sectionSelector)
    .asSequence()
    .map {
      it.children()
    }
    .first()
    .asSequence()
    .filter { it.hasClass(breederListClass) }
    .map { fylkeHTML ->
      val fylke = getFylke(fylkeHTML)
      check(fylke != null)
      getBreeders(fylkeHTML, fylke)
    }
    .flatten()
    .sortedBy { it.fylke }
    .toList()
  breeders.writeToCSV("breeders.csv")

}

fun main() {
  printBreederTable(goldenURL)
}
